import express from  "express";
import { gemini } from "../controllers/gemini.js";
import { readMails, sendMails, sentMails, searchMails, draftMails, archiveMails, junkMails, trashMails, deleteMail, archiveMail, mailBoxInfo, snoozeMail, unArchiveMail, moveToJunk, importantMails, markAsImportant, markAsRead, markAsUnread, deletePermanently, getRefreshToken, getAttachment , isAuthenticated, logout, getRecipient, createLabel } from "../controllers/emailController.js";
const router = express.Router();
router.route("/allEmails").get(isAuthenticated, readMails);
router.route("/send").post(isAuthenticated, sendMails);
router.route("/sentEmails").get(isAuthenticated, sentMails);
router.route("/gemini").get(isAuthenticated, gemini);
router.route("/searchMails").get(isAuthenticated, searchMails);
router.route("/draftMails").get(isAuthenticated, draftMails);
router.route("/archiveMails").get(isAuthenticated, archiveMails);
router.route("/junkMails").get(isAuthenticated, junkMails);
router.route("/trashMails").get(isAuthenticated, trashMails);
router.route("/trash/:id").get(isAuthenticated, deleteMail);
router.route("/delete/:id").get(isAuthenticated, deletePermanently);
router.route("/archive/:id").put(isAuthenticated, archiveMail);
router.route("/getProfile").get(isAuthenticated, mailBoxInfo);
router.route("/snoozeMail").put(isAuthenticated, snoozeMail);
router.route('/archive/:id').put(isAuthenticated, archiveMail);
router.route('/unarchive/:id').put(isAuthenticated, unArchiveMail);
router.route('/junk/:id').put(isAuthenticated, moveToJunk);
router.route('/important/:id').put(isAuthenticated, markAsImportant);
router.route("/importantMails").get(isAuthenticated, importantMails);
router.route("/readMail/:id").put(isAuthenticated, markAsRead);
router.route("/unreadMail/:id").put(isAuthenticated, markAsUnread);
router.route('/create_label').put(isAuthenticated, createLabel);
router.route("/google-auth-code").post(getRefreshToken);
router.route('/logout').get(logout);
router.route("/get_attachment").post(isAuthenticated, getAttachment);
router.route('/getRecipient').get(getRecipient);

export default router;
